import type { Contact } from '../types/contact';

export const seedContacts: Contact[] = [
  {
    id: 'seed-1',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@techcorp.in',
    phone: '+91 98765 43210',
    company: 'TechCorp India',
    notes: 'Lead developer, prefers morning calls.',
    tags: ['Colleague', 'Client'],
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date('2025-01-10').toISOString(),
  },
  {
    id: 'seed-2',
    firstName: 'Arjun',
    lastName: 'Mehta',
    email: 'arjun@startupzone.io',
    phone: '+91 87654 32109',
    company: 'StartupZone',
    notes: 'Potential partnership discussion pending.',
    tags: ['Client', 'Vendor'],
    createdAt: new Date('2025-02-14').toISOString(),
    updatedAt: new Date('2025-02-14').toISOString(),
  },
  {
    id: 'seed-3',
    firstName: 'Neha',
    lastName: 'Gupta',
    email: 'neha.gupta@designhouse.com',
    phone: '+91 76543 21098',
    company: 'Design House',
    notes: 'Freelance designer, great for branding projects.',
    tags: ['Vendor', 'Personal'],
    createdAt: new Date('2025-03-05').toISOString(),
    updatedAt: new Date('2025-03-05').toISOString(),
  },
  {
    id: 'seed-4',
    firstName: 'Rahul',
    lastName: 'Verma',
    email: 'rahul.verma@globalfinance.com',
    phone: '+91 65432 10987',
    company: 'Global Finance',
    notes: 'CFO contact, meets quarterly.',
    tags: ['Client'],
    createdAt: new Date('2025-03-20').toISOString(),
    updatedAt: new Date('2025-03-20').toISOString(),
  },
  {
    id: 'seed-5',
    firstName: 'Ananya',
    lastName: 'Singh',
    email: 'ananya.singh@gmail.com',
    phone: '+91 54321 09876',
    company: '',
    notes: 'College friend, in Bangalore.',
    tags: ['Friend', 'Personal'],
    createdAt: new Date('2025-04-01').toISOString(),
    updatedAt: new Date('2025-04-01').toISOString(),
  },
  {
    id: 'seed-6',
    firstName: 'Vikram',
    lastName: 'Nair',
    email: 'vikram@cloudservices.tech',
    phone: '+91 43210 98765',
    company: 'Cloud Services Tech',
    notes: 'AWS reseller, handles infra procurement.',
    tags: ['Vendor'],
    createdAt: new Date('2025-04-15').toISOString(),
    updatedAt: new Date('2025-04-15').toISOString(),
  },
  {
    id: 'seed-7',
    firstName: 'Kavya',
    lastName: 'Reddy',
    email: 'kavya.reddy@mediapro.in',
    phone: '+91 32109 87654',
    company: 'MediaPro',
    notes: 'Content marketing specialist.',
    tags: ['Colleague'],
    createdAt: new Date('2025-05-10').toISOString(),
    updatedAt: new Date('2025-05-10').toISOString(),
  },
  {
    id: 'seed-8',
    firstName: 'Rohan',
    lastName: 'Patel',
    email: 'rohan.patel@innovatehub.com',
    phone: '+91 21098 76543',
    company: 'InnovateHub',
    notes: 'Investor, interested in Series A.',
    tags: ['Client', 'Other'],
    createdAt: new Date('2025-05-25').toISOString(),
    updatedAt: new Date('2025-05-25').toISOString(),
  },
];
